### ISSUE TITLE
doubt

### ISSUE THREAD

**Issue by Navinca** [venugopalkadamba/Technocolabs-Data-Science-Internship#1]
what does final model.pkl contains?

**Comment by venugopalkadamba** [comment]
It's the predictive model for the credit card default prediction project. The model created in the python notebook is saved as a pickel file to reuse the model.

**Comment by Navinca** [comment]
I am done with mini project 2,actually I am not getting how to deploy the model even though I have watched some YouTube videos ..could you please explain in a step wise manner to deploy ...that would be a great help to me..thanks in advance!Sent from my Samsung Galaxy smartphone.
-------- Original message --------From: Venu Gopal Kadamba <notifications@github.com> Date: 22/10/2020  10:46 pm  (GMT+05:30) To: venugopalkadamba/Technocolabs-Data-Science-Internship <Technocolabs-Data-Science-Internship@noreply.github.com> Cc: Navinca <navinca89@gmail.com>, Author <author@noreply.github.com> Subject: Re: [venugopalkadamba/Technocolabs-Data-Science-Internship] doubt (#1) 
It's the predictive model for the credit card default prediction project. The model created in the python notebook is saved as a pickel file to reuse the model.

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/venugopalkadamba/Technocolabs-Data-Science-Internship/issues/1#issuecomment-714638242",
"url": "https://github.com/venugopalkadamba/Technocolabs-Data-Science-Internship/issues/1#issuecomment-714638242",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by venugopalkadamba** [comment]
Yeah sure. Can you please DM me in LinkedIn, since this is not a repository issue.
